In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

In [2]:
life=pd.read_csv("Life Expectancy Data.csv")
life.columns=['Country', 'Year', 'Status', 'Life Expectancy', 'Adult Mortality',
       'Infant Deaths', 'Alcohol', 'Percentage Expenditure', 'Hepatitis B',
       'Measles', ' BMI', 'Under-Five Deaths', 'Polio', 'Total Expenditure',
       'Diphtheria','HIV/AIDS', 'GDP', 'Population',
       'Thinness  1-19 years', 'Thinness 5-9 years',
       'Income composition of resources', 'Schooling']
life

Country  Year      Status  Life Expectancy  Adult Mortality  \
0     Afghanistan  2015  Developing             65.0            263.0   
1     Afghanistan  2014  Developing             59.9            271.0   
2     Afghanistan  2013  Developing             59.9            268.0   
3     Afghanistan  2012  Developing             59.5            272.0   
4     Afghanistan  2011  Developing             59.2            275.0   
...           ...   ...         ...              ...              ...   
2933     Zimbabwe  2004  Developing             44.3            723.0   
2934     Zimbabwe  2003  Developing             44.5            715.0   
2935     Zimbabwe  2002  Developing             44.8             73.0   
2936     Zimbabwe  2001  Developing             45.3            686.0   
2937     Zimbabwe  2000  Developing             46.0            665.0   

      Infant Deaths  Alcohol  Percentage Expenditure  Hepatitis B  Measles  \
0                62     0.01               71.279624         65.0     1154   
1                64     0.01               73.523582         62.0      492   
2                66     0.01               73.219243         64.0      430   
3                69     0.01               78.184215         67.0     2787   
4                71     0.01                7.097109         68.0     3013   
...             ...      ...                     ...          ...      ...   
2933             27     4.36                0.000000         68.0       31   
2934             26     4.06                0.000000          7.0      998   
2935             25     4.43                0.000000         73.0      304   
2936             25     1.72                0.000000         76.0      529   
2937             24     1.68                0.000000         79.0     1483   

      ...  Polio  Total Expenditure  Diphtheria  HIV/AIDS         GDP  \
0     ...    6.0               8.16        65.0       0.1  584.259210   
1     ...   58.0               8.18        62.0       0.1  612.696514   
2     ...   62.0               8.13        64.0       0.1  631.744976   
3     ...   67.0               8.52        67.0       0.1  669.959000   
4     ...   68.0               7.87        68.0       0.1   63.537231   
...   ...    ...                ...         ...       ...         ...   
2933  ...   67.0               7.13        65.0      33.6  454.366654   
2934  ...    7.0               6.52        68.0      36.7  453.351155   
2935  ...   73.0               6.53        71.0      39.8   57.348340   
2936  ...   76.0               6.16        75.0      42.1  548.587312   
2937  ...   78.0               7.10        78.0      43.5  547.358878   

      Population  Thinness  1-19 years  Thinness 5-9 years  \
0     33736494.0                  17.2                17.3   
1       327582.0                  17.5                17.5   
2     31731688.0                  17.7                17.7   
3      3696958.0                  17.9                18.0   
4      2978599.0                  18.2                18.2   
...          ...                   ...                 ...   
2933  12777511.0                   9.4                 9.4   
2934  12633897.0                   9.8                 9.9   
2935    125525.0                   1.2                 1.3   
2936  12366165.0                   1.6                 1.7   
2937  12222251.0                  11.0                11.2   

      Income composition of resources  Schooling  
0                               0.479       10.1  
1                               0.476       10.0  
2                               0.470        9.9  
3                               0.463        9.8  
4                               0.454        9.5  
...                               ...        ...  
2933                            0.407        9.2  
2934                            0.418        9.5  
2935                            0.427       10.0  
2936                            0.427        9.8  
2937         

In [3]:
def LinearBatchDescent(X,y,Constants,learningRate,limit,Lambda):
    out=y.values
    previousMSE=np.inf
    length=len(X.columns)
    delta=np.zeros(length+1)
    MSE=0
    size=X.shape[0]
    flag=0
    iterations=0
    All_Constants=[]
    while previousMSE-MSE>=limit:
        if flag==0:
            pass
        else:
            previousMSE=MSE
        slopes=Constants[:length]
        c=Constants[length]
        Ypred=X.apply(lambda x: np.sum(np.multiply(x,slopes))+c,axis=1)
        diff=Ypred-y
        delta[:length]=X.apply(lambda x:np.sum(2*x*(diff))/size,axis=0).values.tolist()
        delta[:length] = list(np.array(delta[:length]) + 2 * Lambda * np.array(delta[:length]))
        delta[length]=2*(Ypred-y).sum()/size
        prevConstants=Constants
        Constants=Constants-(delta*learningRate)
        MSE=((diff**2).sum()+Lambda*(np.sum(np.square(Constants))))/size
        flag=1
        iterations=iterations+1
        All_Constants.append(Constants)
    return previousMSE,prevConstants,iterations,All_Constants

def LinearPrediction(X,y,Constants,Lambda):
    out=y.values
    length=len(X.columns)
    slopes=Constants[:length]
    c=Constants[length]
    size=X.shape[0]
    Ypred=X.apply(lambda x: np.sum(np.multiply(x,slopes))+c,axis=1)
    MSE=(((Ypred-out)**2).sum()+Lambda*(np.sum(np.square(Constants))))/size
    return MSE

In [4]:
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
imputedData=imp_median.fit_transform(life[['Life Expectancy','Alcohol','Hepatitis B','Polio','Diphtheria']])
life[['Life Expectancy','Alcohol','Hepatitis B','Polio','Diphtheria']]=imputedData
print(life.isna().sum())

Country                              0
Year                                 0
Status                               0
Life Expectancy                      0
Adult Mortality                     10
Infant Deaths                        0
Alcohol                              0
Percentage Expenditure               0
Hepatitis B                          0
Measles                              0
 BMI                                34
Under-Five Deaths                    0
Polio                                0
Total Expenditure                  226
Diphtheria                           0
HIV/AIDS                             0
GDP                                448
Population                         652
Thinness  1-19 years                34
Thinness 5-9 years                  34
Income composition of resources    167
Schooling                          163
dtype: int64


In [7]:
np.random.rand(length)

array([0.71412257, 0.95880379, 0.51390224, 0.93763644, 0.33583024,
       0.15607157, 0.74435779])

In [8]:
scaler = StandardScaler()
X=life[['Alcohol', 'Hepatitis B','Measles','Polio','Diphtheria', 'HIV/AIDS']]
X=pd.DataFrame(data=scaler.fit_transform(X),columns=X.columns)
y=life['Life Expectancy']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
length=len(X.columns)+1
# Constants=np.random.rand(length)
Constants=np.array([0.71412257, 0.95880379, 0.51390224, 0.93763644, 0.33583024,
       0.15607157, 0.74435779])
learningRate=float(input("Enter the learning Rate you intend to use "))
limit=float(input("Enter the threshold difference between the previousMSE and Current MSE "))
Lambda=float(input("Enter the degree of regularization "))
trainMSE,Constants,iterations,All_weights=LinearBatchDescent(X_train,y_train,Constants,learningRate,limit,Lambda)
testMSE=LinearPrediction(X_test,y_test,Constants,Lambda)
print("The number of iterations for convergence is "+str(iterations))
print("The trainiMSE is "+str(trainMSE)+" and the testMSE is "+str(testMSE))
print("The constants to be used are "+ str(Constants))

Enter the learning Rate you intend to use 0.01
Enter the threshold difference between the previousMSE and Current MSE 0.01
Enter the degree of regularization 0.1
The number of iterations for convergence is 246
The trainiMSE is 39.24926025909454 and the testMSE is 39.72433653651951
The constants to be used are [ 2.66503428 -0.70781388 -0.76941382  1.70922769  2.02868394 -4.52265134
 68.88305805]


In [ ]:
Ridge=Ridge(alpha=0.01,tol=0.01)
Ridge.fit(X_train,y_train)
Predictions=Ridge.predict(X_test)
ActualValues=y_test.values
MSE=(((Predictions-ActualValues)**2).sum()++Lambda*(np.sum(np.square(Constants))))/y_test.shape[0]
print("The MSE obtained after Linear Regression is "+str(MSE))
print("The coefficents are "+str(Ridge.coef_))
print("The intercept is "+str(Ridge.intercept_))

The MSE obtained after Linear Regression is 39.934915704687214
The coefficents are [ 2.67657782 -0.74142491 -0.75410294  1.60541884  2.13897631 -4.53904092]
The intercept is 69.37018500650046


In [14]:
import pandas as pd
import numpy as np

# List of arrays


# Create a DataFrame
df = pd.DataFrame(All_weights, columns=['Alcohol', 'Hepatitis B','Measles','Polio','Diphtheria', 'HIV/AIDS', 'Y-Intercept'])
df['Algo']=['Batch-Gradient']*df.shape[0]
# Display the DataFrame
print(df)

# Save the DataFrame to a CSV file (optional)
df.to_csv('gradient.csv', index=False)



      Alcohol  Hepatitis B   Measles     Polio  Diphtheria  HIV/AIDS  \
0    0.775971     0.966025  0.452974  1.015007    0.420986  0.032844   
1    0.835276     0.970826  0.394649  1.087785    0.501400 -0.086629   
2    0.892159     0.973380  0.338813  1.156221    0.577330 -0.202484   
3    0.946737     0.973848  0.285358  1.220551    0.649024 -0.314852   
4    0.999120     0.972382  0.234181  1.281002    0.716713 -0.423860   
..        ...          ...       ...       ...         ...       ...   
241  2.664289    -0.706457 -0.770180  1.711684    2.026349 -4.521446   
242  2.664542    -0.706917 -0.769921  1.710859    2.027132 -4.521857   
243  2.664791    -0.707369 -0.769665  1.710040    2.027910 -4.522258   
244  2.665034    -0.707814 -0.769414  1.709228    2.028684 -4.522651   
245  2.665273    -0.708251 -0.769166  1.708422    2.029453 -4.523036   

     Y-Intercept            Algo  
0       2.117346  Batch-Gradient  
1       3.462834  Batch-Gradient  
2       4.781373  Batch-Gradie

In [10]:
All_weights


[array([0.77597147, 0.96602465, 0.45297435, 1.0150071 , 0.42098608,
        0.03284382, 2.11734603]),
 array([ 0.83527603,  0.97082604,  0.39464916,  1.08778487,  0.50139964,
        -0.08662875,  3.4628337 ]),
 array([ 0.89215898,  0.97337978,  0.33881321,  1.15622053,  0.57733044,
        -0.2024835 ,  4.7813732 ]),
 array([ 0.9467367 ,  0.97384762,  0.28535825,  1.22055143,  0.64902402,
        -0.31485191,  6.07350579]),
 array([ 0.9991196 ,  0.97238187,  0.23418102,  1.28100226,  0.71671276,
        -0.42385982,  7.33976174]),
 array([ 1.04941243,  0.96912582,  0.185183  ,  1.33778564,  0.78061653,
        -0.52962773,  8.58066063]),
 array([ 1.09771456,  0.96421433,  0.13827019,  1.39110285,  0.84094337,
        -0.63227104,  9.79671151]),
 array([ 1.14412026,  0.95777425,  0.09335287,  1.44114435,  0.89789011,
        -0.7319003 , 10.98841318]),
 array([ 1.18871901,  0.94992485,  0.05034542,  1.48809041,  0.95164299,
        -0.82862141, 12.15625432]),
 array([ 1.23159568e+00,  

In [ ]:
cal_train=pd.read_csv("/content/sample_data/california_housing_train.csv")
cal_test=pd.read_csv("/content/sample_data/california_housing_test.csv")
X_train=cal_train[['housing_median_age','total_rooms','total_bedrooms','population','households','median_income']]
y_train=cal_train['median_house_value']
X_test=cal_test[['housing_median_age','total_rooms','total_bedrooms','population','households','median_income']]
y_test=cal_test['median_house_value']
length=len(X_train.columns)+1
Constants=np.random.rand(length)
learningRate=float(input("Enter the learning Rate you intend to use "))
limit=float(input("Enter the threshold difference between the previousMSE and Current MSE "))
Lambda=float(input("Enter the degree of regularization "))
trainMSE,Constants,iterations=LinearBatchDescent(X_train,y_train,Constants,learningRate,limit,Lambda)
trainMSE=LinearPrediction(X_train,y_train,Constants,Lambda)
testMSE=LinearPrediction(X_test,y_test,Constants,Lambda)
print("The number of iterations for convergence is "+str(iterations))
print("The trainiMSE is "+str(trainMSE)+" and the testMSE is "+str(testMSE))
print("The constants to be used are "+ str(Constants))

Enter the learning Rate you intend to use 0.0001
Enter the threshold difference between the previousMSE and Current MSE 0.00001
Enter the degree of regularization 0.1
The number of iterations for convergence is 2
The trainiMSE is 3.9258165425791034e+17 and the testMSE is 3.7466385104106285e+17
The constants to be used are [1.44936888e+03 1.37639280e+05 2.70113396e+04 6.92744088e+04
 2.52551970e+04 2.29031032e+02 4.13601148e+01]
